services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #ports:
    #  - "8000:8000"
    volumes:
      - ./backend/storage_vol:/app/storage
      - ./backend/chroma_db_vol:/app/chroma_db
      - ./backend/data:/app/data
    environment:
      ENVIRONMENT: prod
    restart: unless-stopped
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_OPTIONS=${NODE_OPTIONS:-"--max_old_space_size=512"}
    #ports:
    #  - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./frontend/.env
      - ./frontend/.env.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  storage:
    driver: local
  chroma_db:
    driver: local
