services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/backend/chroma_db
      - storage_data:/backend/storage
      - ./data:/app/data

    environment:
      ENVIRONMENT: prod

volumes:
  chromadb_data:
    driver: local
  storage_data:
    driver: local
  